name: phase2-release
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - numpy=1.26.4
  - pandas=2.3.2
  - scipy=1.13.1
  - pyyaml=6.0.2
  - biopython=1.84
  - rdkit=2024.3.2
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio=2.6.0
  - pytorch-cuda=12.4
  - pip
  - pip:
      - prodigy-prot==2.4.0
      - OpenMM==8.6.0
      - pdbfixer==1.12.0
      - ImmuneBuilder==1.2
      - ANARCI==2026.2.13.2
      - boltz==2.2.1
